/* The following code was generated by JFlex 1.7.0 */

package analizadores2;
import java_cup.runtime.*;
import proyecto.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/analizadores2/Lexico2.jflex</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRNG = 2;
  public static final int STRNG2 = 4;
  public static final int STRNG3 = 6;
  public static final int COMENT_SIMPLE = 8;
  public static final int COMENT_MULTI = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  1,  1,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\1\1\20\1\21\1\17\22\0\1\2\1\7\1\11"+
    "\4\10\1\13\1\25\1\26\1\16\3\10\1\5\1\15\12\4\1\10"+
    "\1\24\1\23\1\22\3\10\1\32\1\3\1\37\1\3\1\35\1\45"+
    "\1\50\1\3\1\47\2\3\1\34\1\3\1\41\1\40\2\3\1\33"+
    "\1\43\1\36\1\44\1\31\4\3\4\10\1\6\1\10\1\32\1\3"+
    "\1\37\1\3\1\35\1\45\1\50\1\3\1\47\2\3\1\34\1\3"+
    "\1\41\1\40\2\3\1\33\1\43\1\36\1\44\1\31\4\3\1\27"+
    "\1\10\1\30\7\0\1\20\252\0\2\46\115\0\1\42\u1e98\0\1\12"+
    "\3\0\1\14\1\14\12\0\1\20\1\20\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\1\5\6\1\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\6\4\1\1"+
    "\1\4\1\15\1\16\1\17\1\15\1\0\1\20\1\0"+
    "\1\21\2\0\1\21\1\0\1\22\1\23\6\4\2\24"+
    "\1\25\1\26\1\27\1\0\4\4\2\30\1\31\1\0"+
    "\1\4\1\0\1\4\1\32\1\0\1\32\1\4\2\33"+
    "\1\0\1\4\1\0\1\4\3\0\1\34";

  private static int [] zzUnpackAction() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\122\0\173\0\51\0\244\0\244\0\315"+
    "\0\366\0\u011f\0\u0148\0\u0171\0\u019a\0\u01c3\0\u01ec\0\51"+
    "\0\51\0\51\0\51\0\51\0\51\0\51\0\u0215\0\u023e"+
    "\0\u0267\0\u0290\0\u02b9\0\u02e2\0\u030b\0\u0334\0\51\0\51"+
    "\0\51\0\u035d\0\u0386\0\51\0\u0148\0\51\0\u0171\0\u019a"+
    "\0\u019a\0\u01c3\0\51\0\51\0\u03af\0\u03d8\0\u0401\0\u042a"+
    "\0\u0453\0\u047c\0\51\0\315\0\u0386\0\315\0\315\0\u04a5"+
    "\0\u04ce\0\u04f7\0\u0520\0\u0549\0\51\0\315\0\315\0\u0572"+
    "\0\u059b\0\u05c4\0\u05ed\0\51\0\u0616\0\315\0\u063f\0\51"+
    "\0\315\0\u0668\0\u0691\0\u06ba\0\u06e3\0\u070c\0\u0735\0\u075e"+
    "\0\51";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\11\2\5\1\12\1\5"+
    "\1\13\1\14\1\15\1\16\1\17\1\5\1\7\2\0"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\2\10\1\30\1\31\1\32\1\33\2\10\1\5\2\10"+
    "\1\34\1\35\1\36\1\10\51\0\1\37\1\40\50\37"+
    "\1\41\14\37\1\42\1\41\1\0\1\41\27\37\1\0"+
    "\2\7\14\0\1\7\34\0\2\10\1\0\1\10\22\0"+
    "\11\10\1\0\3\10\1\0\2\10\4\0\1\11\1\43"+
    "\65\0\1\44\30\0\7\45\1\46\1\0\1\45\1\0"+
    "\3\45\2\0\20\45\1\0\3\45\1\0\2\45\2\0"+
    "\7\47\1\0\1\46\1\47\1\0\3\47\2\0\20\47"+
    "\1\0\3\47\1\0\2\47\2\0\7\50\2\0\1\51"+
    "\1\0\3\50\2\0\20\50\1\0\3\50\1\0\2\50"+
    "\2\0\7\52\2\0\1\52\1\46\3\52\2\0\20\52"+
    "\1\0\3\52\1\0\2\52\15\0\1\53\1\54\35\0"+
    "\2\10\1\0\1\10\22\0\1\10\1\55\7\10\1\0"+
    "\3\10\1\0\2\10\3\0\2\10\1\0\1\10\22\0"+
    "\4\10\1\56\4\10\1\0\3\10\1\0\2\10\3\0"+
    "\2\10\1\0\1\10\22\0\3\10\1\57\5\10\1\0"+
    "\3\10\1\0\2\10\3\0\2\10\1\0\1\10\22\0"+
    "\2\10\1\60\6\10\1\0\3\10\1\0\2\10\3\0"+
    "\2\10\1\0\1\10\22\0\7\10\1\61\1\10\1\0"+
    "\3\10\1\0\2\10\3\0\2\10\1\0\1\10\22\0"+
    "\1\10\1\62\7\10\1\0\3\10\1\0\2\10\45\0"+
    "\1\63\6\0\2\10\1\0\1\10\22\0\11\10\1\0"+
    "\2\10\1\64\1\0\2\10\15\0\1\40\37\0\1\65"+
    "\47\0\2\10\1\0\1\10\22\0\2\10\1\66\6\10"+
    "\1\0\3\10\1\0\2\10\3\0\2\10\1\0\1\10"+
    "\22\0\5\10\1\67\3\10\1\0\3\10\1\0\2\10"+
    "\3\0\2\10\1\0\1\10\22\0\11\10\1\70\1\71"+
    "\2\10\1\0\2\10\3\0\2\10\1\0\1\10\22\0"+
    "\11\10\1\0\1\10\1\72\1\10\1\0\2\10\3\0"+
    "\2\10\1\0\1\10\22\0\10\10\1\73\1\0\3\10"+
    "\1\0\2\10\3\0\2\10\1\0\1\10\22\0\3\10"+
    "\1\74\5\10\1\0\3\10\1\0\2\10\35\0\1\75"+
    "\16\0\2\10\1\0\1\10\22\0\4\10\1\76\4\10"+
    "\1\0\3\10\1\0\2\10\3\0\2\10\1\0\1\10"+
    "\22\0\4\10\1\77\4\10\1\0\3\10\1\0\2\10"+
    "\3\0\2\10\1\0\1\10\22\0\11\10\1\100\1\101"+
    "\2\10\1\0\2\10\3\0\2\10\1\0\1\10\22\0"+
    "\11\10\1\102\1\103\2\10\1\0\2\10\36\0\1\104"+
    "\1\0\1\105\13\0\2\10\1\0\1\10\22\0\5\10"+
    "\1\106\1\10\1\107\1\10\1\0\3\10\1\0\2\10"+
    "\35\0\1\110\16\0\2\10\1\0\1\10\22\0\4\10"+
    "\1\111\4\10\1\0\3\10\1\0\2\10\34\0\1\112"+
    "\17\0\2\10\1\0\1\10\22\0\3\10\1\113\5\10"+
    "\1\0\3\10\1\0\2\10\35\0\1\114\16\0\2\10"+
    "\1\0\1\10\22\0\4\10\1\115\4\10\1\0\3\10"+
    "\1\0\2\10\5\0\1\116\46\0\2\10\1\116\1\10"+
    "\22\0\11\10\1\0\3\10\1\0\2\10\34\0\1\117"+
    "\54\0\1\120\60\0\1\121";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1927];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\10\2\0\1\11\12\1\7\11\10\1\3\11"+
    "\1\1\1\0\1\11\1\0\1\11\2\0\1\1\1\0"+
    "\2\11\6\1\1\11\4\1\1\0\4\1\1\11\2\1"+
    "\1\0\1\1\1\0\1\1\1\11\1\0\2\1\1\11"+
    "\1\1\1\0\1\1\1\0\1\1\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    String cadena="";
    String comentario = "";

    public void AddError(String tipo, String lexema, int fila, int columna){
        Errores nuevoE= new Errores(tipo, lexema, fila+1, columna+1);
        proyecto.Interfaz.listaErrores.add(nuevoE);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
      
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 206) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.err.println("Error lexico: "+yytext()+ " Linea:"+(yyline)+" Columna:"+(yycolumn));
            AddError("Error Léxico",yytext(),yyline,yycolumn);
            } 
            // fall through
          case 29: break;
          case 2: 
            { yycolumn=1;
            } 
            // fall through
          case 30: break;
          case 3: 
            { /*Se ignoran*/
            } 
            // fall through
          case 31: break;
          case 4: 
            { System.out.println("******************** Id " + yytext());return new Symbol(sym.id,yycolumn,yyline,yytext());
            } 
            // fall through
          case 32: break;
          case 5: 
            { System.out.println("******************** Entero " + yytext());return new Symbol(sym.entero,yycolumn,yyline,yytext());
            } 
            // fall through
          case 33: break;
          case 6: 
            { System.out.println("********************Simbolo" + yytext());return new Symbol(sym.igual,yycolumn,yyline,yytext());
            } 
            // fall through
          case 34: break;
          case 7: 
            { System.out.println("********************Simbolo" + yytext());return new Symbol(sym.menorq,yycolumn,yyline,yytext());
            } 
            // fall through
          case 35: break;
          case 8: 
            { System.out.println("********************Simbolo " + yytext());return new Symbol(sym.puntocoma,yycolumn,yyline,yytext());
            } 
            // fall through
          case 36: break;
          case 9: 
            { System.out.println("********************Simbolo" + yytext());return new Symbol(sym.pariz,yycolumn,yyline,yytext());
            } 
            // fall through
          case 37: break;
          case 10: 
            { System.out.println("********************Simbolo" + yytext());return new Symbol(sym.parder,yycolumn,yyline,yytext());
            } 
            // fall through
          case 38: break;
          case 11: 
            { System.out.println("********************Simbolo" + yytext());return new Symbol(sym.llaveiz,yycolumn,yyline,yytext());
            } 
            // fall through
          case 39: break;
          case 12: 
            { System.out.println("********************Simbolo" + yytext());return new Symbol(sym.llaveder,yycolumn,yyline,yytext());
            } 
            // fall through
          case 40: break;
          case 13: 
            { comentario = comentario + yytext();
            } 
            // fall through
          case 41: break;
          case 14: 
            { yybegin(YYINITIAL); 
    System.out.println(comentario.trim());
    if(proyecto.Interfaz.archivoa == true){
        proyecto.Interfaz.comentariostemp.add(comentario.trim());
    } else {
        comentarioJS nuevov= new comentarioJS(comentario.trim(), proyecto.Interfaz.nombrearchivojs);
        
            for(int i=0;i<proyecto.Interfaz.comentariostemp.size();i++){
                if(proyecto.Interfaz.comentariostemp.get(i).equals(comentario.trim())){
                    proyecto.Interfaz.listacomentariosjs.add(nuevov);
                    i = proyecto.Interfaz.comentariostemp.size();
                }
            }

    }
            } 
            // fall through
          case 42: break;
          case 15: 
            { 
            } 
            // fall through
          case 43: break;
          case 16: 
            { System.out.println("********************Simbolo" + yytext());return new Symbol(sym.diferente,yycolumn,yyline,yytext());
            } 
            // fall through
          case 44: break;
          case 17: 
            { System.out.println("******************** Cadena " + yytext());return new Symbol(sym.cadena,yycolumn,yyline,yytext().substring(1, yytext().length()-1));
            } 
            // fall through
          case 45: break;
          case 18: 
            { yybegin(COMENT_SIMPLE); comentario = "";
            } 
            // fall through
          case 46: break;
          case 19: 
            { yybegin(COMENT_MULTI); comentario = "";
            } 
            // fall through
          case 47: break;
          case 20: 
            { System.out.println("********************Palabra reservada " + yytext());return new Symbol(sym.ifpr,yycolumn,yyline,yytext());
            } 
            // fall through
          case 48: break;
          case 21: 
            { System.out.println("******************** Decimal " + yytext());return new Symbol(sym.decimal,yycolumn,yyline,yytext());
            } 
            // fall through
          case 49: break;
          case 22: 
            { System.out.println("********************Palabra reservada " + yytext());return new Symbol(sym.var,yycolumn,yyline,yytext());
            } 
            // fall through
          case 50: break;
          case 23: 
            { System.out.println("********************Palabra reservada " + yytext());return new Symbol(sym.let,yycolumn,yyline,yytext());
            } 
            // fall through
          case 51: break;
          case 24: 
            { System.out.println("********************Palabra reservada " + yytext());return new Symbol(sym.elsepr,yycolumn,yyline,yytext());
            } 
            // fall through
          case 52: break;
          case 25: 
            { System.out.println("********************Palabra reservada " + yytext());return new Symbol(sym.truevar,yycolumn,yyline,yytext());
            } 
            // fall through
          case 53: break;
          case 26: 
            { System.out.println("********************Palabra reservada " + yytext());return new Symbol(sym.constvar,yycolumn,yyline,yytext());
            } 
            // fall through
          case 54: break;
          case 27: 
            { System.out.println("********************Palabra reservada " + yytext());return new Symbol(sym.falsevar,yycolumn,yyline,yytext());
            } 
            // fall through
          case 55: break;
          case 28: 
            { System.out.println("********************Palabra reservada " + yytext());return new Symbol(sym.imprimir,yycolumn,yyline,yytext());
            } 
            // fall through
          case 56: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
