
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores2;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 5;
  public static final int decimal = 3;
  public static final int llaveiz = 16;
  public static final int forpr = 22;
  public static final int imprimir = 20;
  public static final int falsevar = 12;
  public static final int constvar = 10;
  public static final int menos = 24;
  public static final int igual = 6;
  public static final int EOF = 0;
  public static final int truevar = 11;
  public static final int id = 4;
  public static final int puntocoma = 7;
  public static final int let = 9;
  public static final int elsepr = 19;
  public static final int error = 1;
  public static final int pariz = 14;
  public static final int ifpr = 13;
  public static final int entero = 2;
  public static final int parder = 15;
  public static final int mas = 23;
  public static final int diferente = 21;
  public static final int menorq = 18;
  public static final int var = 8;
  public static final int llaveder = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "entero",
  "decimal",
  "id",
  "cadena",
  "igual",
  "puntocoma",
  "var",
  "let",
  "constvar",
  "truevar",
  "falsevar",
  "ifpr",
  "pariz",
  "parder",
  "llaveiz",
  "llaveder",
  "menorq",
  "elsepr",
  "imprimir",
  "diferente",
  "forpr",
  "mas",
  "menos"
  };
}

