
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores2;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int decimal = 2;
  public static final int cadena = 4;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final int id = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "decimal",
  "id",
  "cadena"
  };
}

